### ISSUE TITLE
To-do list for discontinuing 8.x.x support

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#9001]
Edit this as needed.

#### Before release:
- [x] Update frozen modules (again).

#### Immediately after release:
- [x] Create 9.0.x branch.
- [x] Merge https://github.com/circuitpython/CircuitPython_Library_Screenshot_Maker/issues/16. Adds` /sd` and `settings.toml `to library screenshots.
- [x] Activate version `9.0.x `on ReadTheDocs. The latest semver version automatically becomes the `stable` release on ReadTheDocs.

#### When 8.x is no longer supported:
- [x] Stop building 8.x.x library bundles, by changing https://github.com/adafruit/circuitpython-build-tools/blob/main/circuitpython_build_tools/target_versions.py
- [x] Add last 8.x bundle to https://learn.adafruit.com/welcome-to-circuitpython/frequently-asked-questions#faq-3105289.
- [x] Update bundles list at https://circuitpython.org/libraries .
- [x] Update circup to not download 8.x bundles

**Comment by vladak** [comment]
Nice issue number :-) (sorry, could not resist)
